# These are the default stages. You don't need to explicitly define them. But you could define any stages you need.
stages:
  - build
  - test
  - deploy

# This is the name of the job. You can choose it freely.
maven_build:
  # A job is always executed within a stage. If no stage is set, it defaults to 'test'
  stage: test
  # Since we require Maven for this job, we can restrict the job to runners with a certain tag. Of course, we need to configure a runner with the tag maven with a maven installation
  tags:
    - maven
  only:
    - merge_requests
    - master
  # Here you can execute arbitrate terminal commands.
  # If any of the commands returns a non zero exit code the job fails
  script:
    - echo "Building project with maven"
    - mvn --no-transfer-progress test
    - echo "Generating LOC overview"
    - tokei

generate_artifacts:
  # A job is always executed within a stage. If no stage is set, it defaults to 'test'
  stage: deploy
  # Since we require Maven for this job, we can restrict the job to runners with a certain tag. Of course, we need to configure a runner with the tag maven with a maven installation
  tags:
    - maven
  only:
    - merge_requests
    - master
  # Here you can execute arbitrate terminal commands.
  # If any of the commands returns a non zero exit code the job fails
  script:
    - echo "Building artifacts"
    - mvn --no-transfer-progress package
  artifacts:
    paths:
      - target/Entwurf-1.0-SNAPSHOT.jar
      - target/Entwurf-1.0-SNAPSHOT-jar-with-dependencies.jar
      - target/JavaDoc.zip
    expire_in: 1 month

