@startuml
skinparam monochrome true
hide footbox

participant "main:MainWindow" as main
participant "checkoutView:CheckoutDialogView" as checkoutView
participant "checkout:Checkout" as checkout

activate main
create checkoutView
main --> checkoutView :  <<create>>
main ->checkoutView : show()
activate checkoutView
create checkout
checkoutView -->checkout : <<create>>
checkoutView ->checkout : getTree()
activate checkout
checkout --> checkoutView : gitTree
checkoutView ->checkout : checkout (commit)
checkout -->checkoutView :
deactivate checkout
checkoutView --> main :
deactivate checkoutView

deactivate main

@enduml