@startuml
skinparam monochrome true

package gitclient {
package commands
package controller
package dialogviews
package git{
package exceptions
 }
package levels
package settings
package views {
package filter
}
}
@enduml