@startuml
skinparam monochrome true
hide footbox
participant "p:Pull" as pull
participant "rebase:Rebase" as rebase
participant "facade:GitFacade" as git

create rebase
activate pull
pull -> rebase : <<create>> Rebase(a, b)
pull -> rebase : execute()
activate rebase
create git
rebase -> git : <<create>>
rebase -> git : checkout (a:GitBranch)
activate git
git --> rebase : boolean
rebase -> git : rebase(branch b)
git --> rebase : boolean
deactivate git
rebase --> pull : boolean
deactivate rebase


@enduml