@startuml
skinparam monochrome true
hide footbox

participant "main:MainWindow" as main
participant "checkoutView:CheckoutDialogView" as checkoutView
participant "checkout:Checkout" as checkout
participant "gitFacade:GitFacade" as facade

activate main
create checkoutView
main --> checkoutView :  <<create>>
main ->checkoutView : show()
activate checkoutView
create checkout
checkoutView -->checkout : <<create>>
checkoutView ->checkout : getTree()
activate checkout
create facade
checkout --> facade : <<create>>
checkout -> facade : getBranches()
activate facade
facade --> checkout : List<GitBranch>
checkout -> facade : getCommits()
facade --> checkout : GitCommit[]
checkout --> checkoutView : List<GitBranch>
deactivate facade
checkoutView ->checkout : checkout (commit)
checkout -> checkout : execute()
activate checkout
checkout -> facade : checkout(commit)
activate facade
create JGit
facade --> JGit : <<create>>
facade --> JGit : checkout
activate JGit
JGit -> facade : path
deactivate JGit
facade --> checkout : boolean
deactivate checkout
deactivate facade
checkout -->checkoutView : boolean
deactivate checkout
checkoutView --> main :
deactivate checkoutView

deactivate main

@enduml