@startuml
skinparam monochrome true
hide footbox

actor user
participant "mainStart:Main" as main
participant "persistency:Persistency" as persistency
participant "settings:Settings" as settings
participant "author:GitAuthor" as author
participant "level:Level" as level
participant "settings.txt" as settingstext
participant "data:Data" as data
participant "maiWindow:MainWindow" as mainWindow

create main
user -> main : start program
activate main
create persistency
main --> persistency : <<create>>

main -> persistency : load()
activate persistency
persistency -> settingstext : read file
settingstext -> persistency : File handle

create settings
persistency --> settings : <<create>>
persistency -> settings : getInstance()
activate settings
settings -> settings : new Settings()
settings --> persistency : settings:Settings

alt settings found

persistency -> persistency : restoreSettings()

create data
persistency --> data : <<create>>

persistency -> data : getLevels()
activate data
data --> persistency : levels:List<Level>
deactivate data

loop level:levels
create level
persistency --> level : <<create>>
persistency -> level : getLevelName()
activate level
level --> persistency : name:String
end

persistency -> settings : setLevel (level)
settings --> persistency
deactivate level

create author
persistency --> author : <<create>>
persistency -> author : setName(name)
activate author
author --> persistency
persistency -> author : setEmail(mail)
author --> persistency
deactivate author

persistency -> settings : setAuthor(author)
settings --> persistency

persistency -> settings : setUseTooltips(boolean)
settings --> persistency

persistency -> settings : setShowTreeView
settings --> persistency

persistency -> settings : setActiveRepositoryPath(path)
settings -> persistency



end

persistency --> main
deactivate persistency
deactivate settings
create mainWindow
main --> mainWindow : <<create>>
main -> mainWindow : getView()
activate mainWindow
mainWindow --> main : jPanel
deactivate mainWindow
deactivate main


@enduml