@startuml
skinparam monochrome true
hide footbox

actor user
participant "mainStart:Main" as main
participant "firstuseView:FirstuseView" as firstuse
participant "persistency:Persistency" as persistency
participant "settings:Settings" as settings
participant "author:GitAuthor" as author
participant "level:Level" as level
participant "settings.txt" as settingstext
participant "data:Data" as data
participant "facade:Facade" as git
participant "maiWindow:MainWindow" as mainWindow

create main
user -> main : start program
activate main
create persistency
main --> persistency : <<create>>

main -> persistency : load()
activate persistency
persistency -> settingstext : read file
settingstext -> persistency : File handle

create settings
persistency --> settings : <<create>>
persistency -> settings : getInstance()
activate settings
settings -> settings : new Settings()
settings --> persistency : settings:Settings

alt Einstellungen gefunden

persistency -> persistency : restoreSettings()

create data
persistency --> data : <<create>>

persistency -> data : getLevels()
activate data
data --> persistency : levels:List<Level>
deactivate data

loop level:levels
persistency -> level : getLevelName()
activate level
level --> persistency : name:String
end

persistency -> settings : setLevel (level)
settings --> persistency
deactivate level

create author
persistency --> author : <<create>>
persistency -> author : setName(name)
activate author
author --> persistency
persistency -> author : setEmail(mail)
author --> persistency
deactivate author

persistency -> settings : setAuthor(author)
settings --> persistency

persistency -> settings : setUseTooltips(boolean)
settings --> persistency

persistency -> settings : setShowTreeView
settings --> persistency

persistency -> settings : setActiveRepositoryPath(path)
settings --> persistency

else no settings found
create firstuse
persistency --> firstuse : <<create>>
persistency -> firstuse : getView()
activate firstuse
firstuse --> persistency : panel:JPanel
create author
firstuse --> author : <<create>>
firstuse ->  author : setName(name:String)
author --> firstuse
firstuse -> author : setEmail(mail:String)
author --> firstuse
firstuse -> settings : setAuthor(author:Author)
settings --> firstuse
firstuse -> settings : setActiveRepositoryPath(path:String)

alt Ordner ohne Repository ausgewählt
create git
settings --> git : <<create>>
settings -> git : initializeRepository(path:String)
activate git
git --> settings : boolean
else Ordner mit Repository ausgewählt
deactivate git
settings -> git:  setRepositoryPath(path:String)
activate git
git --> settings : boolean
deactivate git
end
end
settings --> main


persistency --> main
deactivate persistency
deactivate settings
create mainWindow
main --> mainWindow : <<create>>
main -> mainWindow : getView()
activate mainWindow
mainWindow --> main : jPanel
deactivate mainWindow
deactivate main


@enduml